import type { ComponentEntry } from "./types.ts";

const cn = { clsx: "^2.1.0", "tailwind-merge": "^2.5.0" } as const;
const cva = { "class-variance-authority": "^0.7.0" } as const;
const lucide = { "lucide-react": "^0.400.0" } as const;

export const components: ComponentEntry[] = [
	{
		name: "hello",
		spec: "ui/phase-0/00-cli-add#fixture",
		phase: 0,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "__fixtures__/hello.tsx", to: "hello.tsx" }],
		peerDeps: {},
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "alert",
		spec: "ui/phase-1/02-alert",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "alert.tsx", to: "alert.tsx" }],
		peerDeps: { ...cn, ...cva },
		internalHelpers: ["cn", "variants"],
		tokens: ["base"],
	},
	{
		name: "aspect-ratio",
		spec: "ui/phase-1/04-aspect-ratio",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "aspect-ratio.tsx", to: "aspect-ratio.tsx" }],
		peerDeps: { ...cn },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "badge",
		spec: "ui/phase-1/06-badge",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "badge.tsx", to: "badge.tsx" }],
		peerDeps: { ...cn, ...cva },
		internalHelpers: ["cn", "slot", "variants"],
		tokens: ["base"],
	},
	{
		name: "breadcrumb",
		spec: "ui/phase-1/07-breadcrumb",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "breadcrumb.tsx", to: "breadcrumb.tsx" }],
		peerDeps: { ...cn, ...lucide },
		internalHelpers: ["cn", "slot"],
		tokens: ["base"],
	},
	{
		name: "button-group",
		spec: "ui/phase-1/09-button-group",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "button-group.tsx", to: "button-group.tsx" }],
		peerDeps: { ...cn, ...cva },
		internalHelpers: ["cn", "variants"],
		tokens: ["base"],
	},
	{
		name: "card",
		spec: "ui/phase-1/11-card",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "card.tsx", to: "card.tsx" }],
		peerDeps: { ...cn },
		internalHelpers: ["cn", "slot"],
		tokens: ["base"],
	},
	{
		name: "direction",
		spec: "ui/phase-1/22-direction",
		phase: 1,
		kind: "provider",
		island: "no",
		status: "completed",
		files: [{ from: "direction.tsx", to: "direction.tsx" }],
		peerDeps: { "@radix-ui/react-direction": "^1.1.0" },
		internalHelpers: [],
		tokens: ["base"],
	},
	{
		name: "empty",
		spec: "ui/phase-1/25-empty",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "empty.tsx", to: "empty.tsx" }],
		peerDeps: { ...cn, ...cva },
		internalHelpers: ["cn", "variants"],
		tokens: ["base"],
	},
	{
		name: "input-group",
		spec: "ui/phase-1/30-input-group",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "input-group.tsx", to: "input-group.tsx" }],
		peerDeps: { ...cn, ...cva },
		internalHelpers: ["cn", "variants"],
		tokens: ["base"],
	},
	{
		name: "item",
		spec: "ui/phase-1/32-item",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "item.tsx", to: "item.tsx" }],
		peerDeps: { ...cn, ...cva },
		internalHelpers: ["cn", "slot", "variants"],
		tokens: ["base"],
	},
	{
		name: "kbd",
		spec: "ui/phase-1/33-kbd",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "kbd.tsx", to: "kbd.tsx" }],
		peerDeps: { ...cn },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "label",
		spec: "ui/phase-1/34-label",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "label.tsx", to: "label.tsx" }],
		peerDeps: { ...cn, "@radix-ui/react-label": "^2.1.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "pagination",
		spec: "ui/phase-1/38-pagination",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "pagination.tsx", to: "pagination.tsx" }],
		peerDeps: { ...cn, ...cva, ...lucide },
		internalHelpers: ["cn", "variants"],
		tokens: ["base"],
	},
	{
		name: "separator",
		spec: "ui/phase-1/45-separator",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "separator.tsx", to: "separator.tsx" }],
		peerDeps: { ...cn, "@radix-ui/react-separator": "^1.1.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "skeleton",
		spec: "ui/phase-1/48-skeleton",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "skeleton.tsx", to: "skeleton.tsx" }],
		peerDeps: { ...cn },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "spinner",
		spec: "ui/phase-1/51-spinner",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "spinner.tsx", to: "spinner.tsx" }],
		peerDeps: { ...cn, ...cva, ...lucide },
		internalHelpers: ["cn", "variants"],
		tokens: ["base"],
	},
	{
		name: "table",
		spec: "ui/phase-1/53-table",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "table.tsx", to: "table.tsx" }],
		peerDeps: { ...cn },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "typography",
		spec: "ui/phase-1/60-typography",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "typography.tsx", to: "typography.tsx" }],
		peerDeps: { ...cn },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
];
