import type { ComponentEntry } from "./types.ts";

const cn = { clsx: "^2.1.0", "tailwind-merge": "^2.5.0" } as const;
const cva = { "class-variance-authority": "^0.7.0" } as const;
const lucide = { "lucide-react": "^0.400.0" } as const;

export const components: ComponentEntry[] = [
	{
		name: "hello",
		spec: "ui/phase-0/00-cli-add#fixture",
		phase: 0,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "__fixtures__/hello.tsx", to: "hello.tsx" }],
		peerDeps: {},
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "alert",
		spec: "ui/phase-1/02-alert",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "alert.tsx", to: "alert.tsx" }],
		peerDeps: { ...cn, ...cva },
		internalHelpers: ["cn", "variants"],
		tokens: ["base"],
	},
	{
		name: "aspect-ratio",
		spec: "ui/phase-1/04-aspect-ratio",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "aspect-ratio.tsx", to: "aspect-ratio.tsx" }],
		peerDeps: { ...cn },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "badge",
		spec: "ui/phase-1/06-badge",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "badge.tsx", to: "badge.tsx" }],
		peerDeps: { ...cn, ...cva },
		internalHelpers: ["cn", "slot", "variants"],
		tokens: ["base"],
	},
	{
		name: "breadcrumb",
		spec: "ui/phase-1/07-breadcrumb",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "breadcrumb.tsx", to: "breadcrumb.tsx" }],
		peerDeps: { ...cn, ...lucide },
		internalHelpers: ["cn", "slot"],
		tokens: ["base"],
	},
	{
		name: "button-group",
		spec: "ui/phase-1/09-button-group",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "button-group.tsx", to: "button-group.tsx" }],
		peerDeps: { ...cn, ...cva },
		internalHelpers: ["cn", "variants"],
		tokens: ["base"],
	},
	{
		name: "card",
		spec: "ui/phase-1/11-card",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "card.tsx", to: "card.tsx" }],
		peerDeps: { ...cn },
		internalHelpers: ["cn", "slot"],
		tokens: ["base"],
	},
	{
		name: "direction",
		spec: "ui/phase-1/22-direction",
		phase: 1,
		kind: "provider",
		island: "no",
		status: "completed",
		files: [{ from: "direction.tsx", to: "direction.tsx" }],
		peerDeps: { "@radix-ui/react-direction": "^1.1.0" },
		internalHelpers: [],
		tokens: ["base"],
	},
	{
		name: "empty",
		spec: "ui/phase-1/25-empty",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "empty.tsx", to: "empty.tsx" }],
		peerDeps: { ...cn, ...cva },
		internalHelpers: ["cn", "variants"],
		tokens: ["base"],
	},
	{
		name: "input-group",
		spec: "ui/phase-1/30-input-group",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		// input-group's button composes buttonVariants, so button.tsx is co-stamped.
		files: [
			{ from: "input-group.tsx", to: "input-group.tsx" },
			{ from: "button.tsx", to: "button.tsx" },
		],
		peerDeps: { ...cn, ...cva },
		internalHelpers: ["cn", "slot", "variants"],
		tokens: ["base"],
	},
	{
		name: "item",
		spec: "ui/phase-1/32-item",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "item.tsx", to: "item.tsx" }],
		peerDeps: { ...cn, ...cva },
		internalHelpers: ["cn", "slot", "variants"],
		tokens: ["base"],
	},
	{
		name: "kbd",
		spec: "ui/phase-1/33-kbd",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "kbd.tsx", to: "kbd.tsx" }],
		peerDeps: { ...cn },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "label",
		spec: "ui/phase-1/34-label",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "label.tsx", to: "label.tsx" }],
		peerDeps: { ...cn, "@radix-ui/react-label": "^2.1.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "pagination",
		spec: "ui/phase-1/38-pagination",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		// PaginationLink composes buttonVariants, so button.tsx is co-stamped.
		files: [
			{ from: "pagination.tsx", to: "pagination.tsx" },
			{ from: "button.tsx", to: "button.tsx" },
		],
		peerDeps: { ...cn, ...cva, ...lucide },
		internalHelpers: ["cn", "slot", "variants"],
		tokens: ["base"],
	},
	{
		name: "separator",
		spec: "ui/phase-1/45-separator",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "separator.tsx", to: "separator.tsx" }],
		peerDeps: { ...cn, "@radix-ui/react-separator": "^1.1.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "skeleton",
		spec: "ui/phase-1/48-skeleton",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "skeleton.tsx", to: "skeleton.tsx" }],
		peerDeps: { ...cn },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "spinner",
		spec: "ui/phase-1/51-spinner",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "spinner.tsx", to: "spinner.tsx" }],
		peerDeps: { ...cn, ...cva, ...lucide },
		internalHelpers: ["cn", "variants"],
		tokens: ["base"],
	},
	{
		name: "table",
		spec: "ui/phase-1/53-table",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "table.tsx", to: "table.tsx" }],
		peerDeps: { ...cn },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "typography",
		spec: "ui/phase-1/60-typography",
		phase: 1,
		kind: "primitive",
		island: "no",
		status: "completed",
		files: [{ from: "typography.tsx", to: "typography.tsx" }],
		peerDeps: { ...cn },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "button",
		spec: "ui/phase-2/08-button",
		phase: 2,
		kind: "primitive",
		island: "subtree",
		status: "completed",
		files: [{ from: "button.tsx", to: "button.tsx" }],
		peerDeps: { ...cn, ...cva },
		internalHelpers: ["cn", "slot", "variants"],
		tokens: ["base"],
	},
	{
		name: "checkbox",
		spec: "ui/phase-2/14-checkbox",
		phase: 2,
		kind: "primitive",
		island: "yes-downgrade",
		status: "completed",
		files: [{ from: "checkbox.tsx", to: "checkbox.tsx" }],
		peerDeps: { ...cn, ...lucide, "@radix-ui/react-checkbox": "^1.1.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "field",
		spec: "ui/phase-2/26-field",
		phase: 2,
		kind: "primitive",
		island: "yes",
		status: "completed",
		files: [{ from: "field.tsx", to: "field.tsx" }],
		peerDeps: { ...cn, "@radix-ui/react-label": "^2.1.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "form",
		spec: "ui/phase-2/27-form",
		phase: 2,
		kind: "recipe",
		island: "yes",
		status: "completed",
		files: [{ from: "form.tsx", to: "form.tsx" }],
		peerDeps: {
			...cn,
			"@radix-ui/react-label": "^2.1.0",
			"react-hook-form": "^7.53.0",
			"@hookform/resolvers": "^5.0.0",
			zod: "^4.0.0",
		},
		internalHelpers: ["cn", "slot"],
		tokens: ["base"],
	},
	{
		name: "input",
		spec: "ui/phase-2/29-input",
		phase: 2,
		kind: "primitive",
		island: "yes-downgrade",
		status: "completed",
		files: [{ from: "input.tsx", to: "input.tsx" }],
		peerDeps: { ...cn },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "native-select",
		spec: "ui/phase-2/36-native-select",
		phase: 2,
		kind: "primitive",
		island: "yes-downgrade",
		status: "completed",
		files: [{ from: "native-select.tsx", to: "native-select.tsx" }],
		peerDeps: { ...cn },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "progress",
		spec: "ui/phase-2/40-progress",
		phase: 2,
		kind: "primitive",
		island: "yes-downgrade",
		status: "completed",
		files: [{ from: "progress.tsx", to: "progress.tsx" }],
		peerDeps: { ...cn, "@radix-ui/react-progress": "^1.1.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "radio-group",
		spec: "ui/phase-2/41-radio-group",
		phase: 2,
		kind: "primitive",
		island: "yes-downgrade",
		status: "completed",
		files: [{ from: "radio-group.tsx", to: "radio-group.tsx" }],
		peerDeps: { ...cn, ...lucide, "@radix-ui/react-radio-group": "^1.2.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "slider",
		spec: "ui/phase-2/49-slider",
		phase: 2,
		kind: "primitive",
		island: "yes-downgrade",
		status: "completed",
		files: [{ from: "slider.tsx", to: "slider.tsx" }],
		peerDeps: { ...cn, "@radix-ui/react-slider": "^1.2.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "switch",
		spec: "ui/phase-2/52-switch",
		phase: 2,
		kind: "primitive",
		island: "yes-downgrade",
		status: "completed",
		files: [{ from: "switch.tsx", to: "switch.tsx" }],
		peerDeps: { ...cn, "@radix-ui/react-switch": "^1.1.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "textarea",
		spec: "ui/phase-2/55-textarea",
		phase: 2,
		kind: "primitive",
		island: "yes-downgrade",
		status: "completed",
		files: [{ from: "textarea.tsx", to: "textarea.tsx" }],
		peerDeps: { ...cn },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "toggle",
		spec: "ui/phase-2/57-toggle",
		phase: 2,
		kind: "primitive",
		island: "yes-downgrade",
		status: "completed",
		files: [{ from: "toggle.tsx", to: "toggle.tsx" }],
		peerDeps: { ...cn, ...cva, "@radix-ui/react-toggle": "^1.1.0" },
		internalHelpers: ["cn", "variants"],
		tokens: ["base"],
	},
	{
		name: "accordion",
		spec: "ui/phase-3/01-accordion",
		phase: 3,
		kind: "primitive",
		island: "yes",
		status: "completed",
		files: [{ from: "accordion.tsx", to: "accordion.tsx" }],
		peerDeps: { ...cn, ...lucide, "@radix-ui/react-accordion": "^1.2.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "alert-dialog",
		spec: "ui/phase-3/03-alert-dialog",
		phase: 3,
		kind: "primitive",
		island: "yes",
		status: "completed",
		files: [{ from: "alert-dialog.tsx", to: "alert-dialog.tsx" }],
		peerDeps: { ...cn, "@radix-ui/react-alert-dialog": "^1.1.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "avatar",
		spec: "ui/phase-3/05-avatar",
		phase: 3,
		kind: "primitive",
		island: "yes",
		status: "completed",
		files: [{ from: "avatar.tsx", to: "avatar.tsx" }],
		peerDeps: { ...cn, "@radix-ui/react-avatar": "^1.1.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "collapsible",
		spec: "ui/phase-3/15-collapsible",
		phase: 3,
		kind: "primitive",
		island: "yes",
		status: "completed",
		files: [{ from: "collapsible.tsx", to: "collapsible.tsx" }],
		peerDeps: { ...cn, "@radix-ui/react-collapsible": "^1.1.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "context-menu",
		spec: "ui/phase-3/18-context-menu",
		phase: 3,
		kind: "primitive",
		island: "yes",
		status: "completed",
		files: [{ from: "context-menu.tsx", to: "context-menu.tsx" }],
		peerDeps: { ...cn, ...lucide, "@radix-ui/react-context-menu": "^2.2.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "dialog",
		spec: "ui/phase-3/21-dialog",
		phase: 3,
		kind: "primitive",
		island: "yes",
		status: "completed",
		files: [{ from: "dialog.tsx", to: "dialog.tsx" }],
		peerDeps: { ...cn, ...lucide, "@radix-ui/react-dialog": "^1.1.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "drawer",
		spec: "ui/phase-3/23-drawer",
		phase: 3,
		kind: "primitive",
		island: "yes",
		status: "completed",
		files: [{ from: "drawer.tsx", to: "drawer.tsx" }],
		peerDeps: { ...cn, vaul: "^1.0.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "dropdown-menu",
		spec: "ui/phase-3/24-dropdown-menu",
		phase: 3,
		kind: "primitive",
		island: "yes",
		status: "completed",
		files: [{ from: "dropdown-menu.tsx", to: "dropdown-menu.tsx" }],
		peerDeps: { ...cn, ...lucide, "@radix-ui/react-dropdown-menu": "^2.1.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "hover-card",
		spec: "ui/phase-3/28-hover-card",
		phase: 3,
		kind: "primitive",
		island: "yes",
		status: "completed",
		files: [{ from: "hover-card.tsx", to: "hover-card.tsx" }],
		peerDeps: { ...cn, "@radix-ui/react-hover-card": "^1.1.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "input-otp",
		spec: "ui/phase-3/31-input-otp",
		phase: 3,
		kind: "primitive",
		island: "yes",
		status: "completed",
		files: [{ from: "input-otp.tsx", to: "input-otp.tsx" }],
		peerDeps: { ...cn, ...lucide, "input-otp": "^1.4.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "menubar",
		spec: "ui/phase-3/35-menubar",
		phase: 3,
		kind: "primitive",
		island: "yes",
		status: "completed",
		files: [{ from: "menubar.tsx", to: "menubar.tsx" }],
		peerDeps: { ...cn, ...lucide, "@radix-ui/react-menubar": "^1.1.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "navigation-menu",
		spec: "ui/phase-3/37-navigation-menu",
		phase: 3,
		kind: "primitive",
		island: "yes",
		status: "completed",
		files: [{ from: "navigation-menu.tsx", to: "navigation-menu.tsx" }],
		peerDeps: {
			...cn,
			...cva,
			...lucide,
			"@radix-ui/react-navigation-menu": "^1.2.0",
		},
		internalHelpers: ["cn", "variants"],
		tokens: ["base"],
	},
	{
		name: "popover",
		spec: "ui/phase-3/39-popover",
		phase: 3,
		kind: "primitive",
		island: "yes",
		status: "completed",
		files: [{ from: "popover.tsx", to: "popover.tsx" }],
		peerDeps: { ...cn, "@radix-ui/react-popover": "^1.1.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "scroll-area",
		spec: "ui/phase-3/43-scroll-area",
		phase: 3,
		kind: "primitive",
		island: "yes",
		status: "completed",
		files: [{ from: "scroll-area.tsx", to: "scroll-area.tsx" }],
		peerDeps: { ...cn, "@radix-ui/react-scroll-area": "^1.2.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "select",
		spec: "ui/phase-3/44-select",
		phase: 3,
		kind: "primitive",
		island: "yes",
		status: "completed",
		files: [{ from: "select.tsx", to: "select.tsx" }],
		peerDeps: { ...cn, ...lucide, "@radix-ui/react-select": "^2.1.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "sheet",
		spec: "ui/phase-3/46-sheet",
		phase: 3,
		kind: "primitive",
		island: "yes",
		status: "completed",
		files: [{ from: "sheet.tsx", to: "sheet.tsx" }],
		peerDeps: { ...cn, ...cva, ...lucide, "@radix-ui/react-dialog": "^1.1.0" },
		internalHelpers: ["cn", "variants"],
		tokens: ["base"],
	},
	{
		name: "sonner",
		spec: "ui/phase-3/50-sonner",
		phase: 3,
		kind: "primitive",
		island: "yes",
		status: "completed",
		files: [{ from: "sonner.tsx", to: "sonner.tsx" }],
		peerDeps: { sonner: "^1.5.0" },
		internalHelpers: [],
		tokens: ["base"],
	},
	{
		name: "tabs",
		spec: "ui/phase-3/54-tabs",
		phase: 3,
		kind: "primitive",
		island: "yes",
		status: "completed",
		files: [{ from: "tabs.tsx", to: "tabs.tsx" }],
		peerDeps: { ...cn, "@radix-ui/react-tabs": "^1.1.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "toast",
		spec: "ui/phase-3/56-toast",
		phase: 3,
		kind: "primitive",
		island: "yes",
		status: "completed",
		files: [{ from: "toast.tsx", to: "toast.tsx" }],
		peerDeps: { ...cn, ...cva, ...lucide, "@radix-ui/react-toast": "^1.2.0" },
		internalHelpers: ["cn", "variants"],
		tokens: ["base"],
	},
	{
		name: "toggle-group",
		spec: "ui/phase-3/58-toggle-group",
		phase: 3,
		kind: "primitive",
		island: "yes",
		status: "completed",
		// ToggleGroupItem composes toggleVariants, so toggle.tsx is co-stamped.
		files: [
			{ from: "toggle-group.tsx", to: "toggle-group.tsx" },
			{ from: "toggle.tsx", to: "toggle.tsx" },
		],
		peerDeps: {
			...cn,
			...cva,
			"@radix-ui/react-toggle": "^1.1.0",
			"@radix-ui/react-toggle-group": "^1.1.0",
		},
		internalHelpers: ["cn", "variants"],
		tokens: ["base"],
	},
	{
		name: "tooltip",
		spec: "ui/phase-3/59-tooltip",
		phase: 3,
		kind: "primitive",
		island: "yes",
		status: "completed",
		files: [{ from: "tooltip.tsx", to: "tooltip.tsx" }],
		peerDeps: { ...cn, "@radix-ui/react-tooltip": "^1.1.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "calendar",
		spec: "ui/phase-4/10-calendar",
		phase: 4,
		kind: "primitive",
		island: "yes",
		status: "completed",
		// nav buttons compose buttonVariants, so button.tsx is co-stamped.
		files: [
			{ from: "calendar.tsx", to: "calendar.tsx" },
			{ from: "button.tsx", to: "button.tsx" },
		],
		peerDeps: {
			...cn,
			...cva,
			...lucide,
			"react-day-picker": "^9.0.0",
			"date-fns": "^4.1.0",
		},
		internalHelpers: ["cn", "slot", "variants"],
		tokens: ["base"],
	},
	{
		name: "carousel",
		spec: "ui/phase-4/12-carousel",
		phase: 4,
		kind: "primitive",
		island: "yes",
		status: "completed",
		// prev/next controls are Buttons, so button.tsx is co-stamped.
		files: [
			{ from: "carousel.tsx", to: "carousel.tsx" },
			{ from: "button.tsx", to: "button.tsx" },
		],
		peerDeps: { ...cn, ...cva, ...lucide, "embla-carousel-react": "^8.3.0" },
		internalHelpers: ["cn", "slot", "variants"],
		tokens: ["base"],
	},
	{
		name: "chart",
		spec: "ui/phase-4/13-chart",
		phase: 4,
		kind: "primitive",
		island: "yes",
		status: "completed",
		files: [{ from: "chart.tsx", to: "chart.tsx" }],
		peerDeps: { ...cn, recharts: "^2.13.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "command",
		spec: "ui/phase-4/17-command",
		phase: 4,
		kind: "primitive",
		island: "yes",
		status: "completed",
		files: [{ from: "command.tsx", to: "command.tsx" }],
		peerDeps: {
			...cn,
			...lucide,
			cmdk: "^1.0.0",
			"@radix-ui/react-dialog": "^1.1.0",
		},
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
	{
		name: "resizable",
		spec: "ui/phase-4/42-resizable",
		phase: 4,
		kind: "primitive",
		island: "yes",
		status: "completed",
		files: [{ from: "resizable.tsx", to: "resizable.tsx" }],
		peerDeps: { ...cn, ...lucide, "react-resizable-panels": "^2.1.0" },
		internalHelpers: ["cn"],
		tokens: ["base"],
	},
];
